// <auto-generated />
namespace CommonNews.Data.Common
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Nowo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Nowo));
        
        string IMigrationMetadata.Id
        {
            get { return "201710131222334_Nowo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
